### ISSUE TITLE
Error 400. Недопустимый запрос

### ISSUE THREAD

**Issue by sosalker** [leadvertex/sharex-custom-uploader#1]
Почему?

**Comment by sosalker** [comment]
Токен юзернейм сделал

**Comment by sosalker** [comment]
И при тесте пишет POST пуст

**Comment by XAKEPEHOK** [comment]
Добрый день. Вряд ли мы вам сейчас здесь что-то подскажем. Код писал джун, который сейчас с нами не работает, а мы используем другое решение

**Comment by sosalker** [comment]
Проблема на моей стороне
